name: standard
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  standard:
    uses: bounded-systems/.github/.github/workflows/repo-standard.yml@63715f952022f2edfef72c0a4a0ec94e48e51e71
    with:
      security: true
      test: true
      runtime: bun
      test-command: "bun install --frozen-lockfile && bun test"
